// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: telemetry/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StreamService_GetLiveStream_FullMethodName = "/telemetry.StreamService/GetLiveStream"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	GetLiveStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (StreamService_GetLiveStreamClient, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) GetLiveStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (StreamService_GetLiveStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_GetLiveStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceGetLiveStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamService_GetLiveStreamClient interface {
	Recv() (*TelemetryPoint, error)
	grpc.ClientStream
}

type streamServiceGetLiveStreamClient struct {
	grpc.ClientStream
}

func (x *streamServiceGetLiveStreamClient) Recv() (*TelemetryPoint, error) {
	m := new(TelemetryPoint)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility
type StreamServiceServer interface {
	GetLiveStream(*emptypb.Empty, StreamService_GetLiveStreamServer) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (UnimplementedStreamServiceServer) GetLiveStream(*emptypb.Empty, StreamService_GetLiveStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLiveStream not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_GetLiveStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).GetLiveStream(m, &streamServiceGetLiveStreamServer{stream})
}

type StreamService_GetLiveStreamServer interface {
	Send(*TelemetryPoint) error
	grpc.ServerStream
}

type streamServiceGetLiveStreamServer struct {
	grpc.ServerStream
}

func (x *streamServiceGetLiveStreamServer) Send(m *TelemetryPoint) error {
	return x.ServerStream.SendMsg(m)
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLiveStream",
			Handler:       _StreamService_GetLiveStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "telemetry/telemetry.proto",
}
